[workspace]

members = [
    "packages/qwik/src/napi",
    "packages/qwik/src/optimizer/cli",
    "packages/qwik/src/optimizer/core",
]
exclude = ["packages/qwik/src/wasm"]

[profile.release]
debug = 0

