[package]
authors = ["Manu <manu@builder.io>"]
name = "qwik-core"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/BuilderIO/qwik"
license = "MIT"
description = "Qwik optimizer compiler"
keywords = ["qwik", "swc", "javascript", "optimizer", "compiler"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[lib]
crate-type = ["rlib"]

[dependencies]
swc_ecmascript = { version = "0.156.0", features = ["parser", "transforms", "module", "typescript", "optimization", "minifier", "react", "utils", "visit", "codegen", "utils"] }
swc_common = { version = "0.18.1", features = ["sourcemap"] }
swc_atoms = "0.2.11"
serde = "1.0.137"
serde_bytes = "0.11.6"
serde_json = "1.0.81"
simple-error = "0.2.3"
base64 = "0.13.0"
pathdiff = "0.2.1"
relative-path = "1.7.0"
lazy_static = "1.4.0"
anyhow = "1.0.57"
derivative = "2.2.0"
rayon = "1.5.1"
path-slash="0.1.4"

[dev-dependencies]
insta = "1.14.0"

[features]
fs=[]
parallel=[]
